### PR TITLE
Initial checkin of Nov01 conventional data

### PR DESCRIPTION
**Pull request by gthompsnJCSDA**
## Description

Data in this PR is provided by Francois.  These files compliment the obs_sprint by OBS team members during the code sprints of Dec2020/Jan2021 to finalize the QC steps of conventional data.  A separate PR is forthcoming for the QC yaml files that utilize all of the medium-size files included by this PR.

### Issue(s) addressed

No issue was opened just for this step.

## Dependencies

None

## Impact

No impacts to other repos

## Test Data

This fulfills the test data need for ioda obs and geoval files.

### CODE REVIEW

**Review by huishao-r — APPROVED** [review]
@gthompsnJCSDA Do we need both _s and _m files? For ctest, we only need one of them as I understand?

**Comment by gthompsnJCSDA** [comment]
> @gthompsnJCSDA Do we need both _s and _m files? For ctest, we only need one of them as I understand?

While true (what you said), the _s files are super tiny and some users may wish to test on something even smaller. So I think it's a good idea to keep both.

**Comment by gthompsnJCSDA** [comment]
@srherbener @fcvdb @rhoneyager @dickdee   Have I mis-understood something about how this works?  I submitted the PR 12 days ago and need this to happen as it is holding up my PR#740 (UFO).  While I understand that Steve H. (and perhaps others) gets relief from quite a number of repetitive requests to update the test data, I thought this new technique was designed to help improve the method of updating UFO/IODA test data directly.  At the moment, I feel a 12-day process is unacceptably too slow.

**Comment by huishao-r** [comment]
@gthompsnJCSDA @rhoneyager This PR is outdated since it points to the ufo-data-old. I am closing this issue since it is under code sprint Epic. Please address this in a new issue under AOP21 if necessary.

**Pull request closed without merging**
