### PR TITLE
Ufo-data repo

### PR DESCRIPTION
**Pull request by mmiesch**
## Description

This creates a new LFS-enabled repo to store and distribute the ufo tier 1 test data

As we discussed, an attempt was made to make this contain the data needed to run the ufo tier 1 tests.  So, many files that had been in the ioda test data have been moved here instead because they are not required for ioda.

However, I did not want to duplicate data.  There are a dozen files or so that are used by both ioda and ufo tests.  I have left them in ioda.  So, the ufo tests still require the ioda test data.  But, the ioda test data is much smaller than it was before.

### Issue(s) addressed

- fixes #https://github.com/JCSDA-internal/ioda/issues/77

## Acceptance Criteria (Definition of Done)

All ufo tests pass when this repository is cloned with the name:

```bash
<parent-directory>/ufo/develop
```

and `LOCAL_PATH_JEDI_TESTFILES` set to `<parent-directory>`.  Note that you also have to include the ioda data (now from the ioda-data repo) and the crtm data in the test file directory as well (and also saber if you are building it - I tested without it).

## Dependencies

None

## Impact

- [x] ufo

## Test Data

No test data needs to be updated on AWS - this replaces the AWS test data

### CODE REVIEW

**Comment by shlyaeva** [comment]
Do we want to have CRTM coefficients that are used in the ufo tests here too, to avoid downloading CRTM data, or is it OK to download CRTM data?

**Review by ytremolet — APPROVED** [review]

**Review by srherbener — APPROVED** [review]

**Comment by mmiesch** [comment]
> Do we want to have CRTM coefficients that are used in the ufo tests here too, to avoid downloading CRTM data, or is it OK to download CRTM data?

Since the CRTM coefficient data doesn't change that often, I think it is best to get the latest release from UCAR DASH.  This would save us the trouble of updating ufo-data when these change and it would save on egress costs, since we do not pay for UCAR DASH.

**Comment by mmiesch** [comment]
This has two approvals but let's hold off on merging.  I want to eliminate the ioda-data dependency as suggested by @srherbener

**Comment by mmiesch** [comment]
Ok - all ufo tests are passing again.  This has been modified so it has all the data files needed for ufo; there is no dependence of ufo tests on ioda-data.

**Review by rhoneyager — APPROVED** [review]

**Pull request merged**
